### PR TITLE
Fix for haxe 3.3 macro execution order

### PR DESCRIPTION
**Pull request by ntrf**
Fixes https://github.com/underscorediscovery/snow/issues/91 and https://github.com/underscorediscovery/luxe/issues/383

Probably it's a haxe bug that `Context.getType` can't access other types during building, even if types aren't forming cyclic references. Instead i'm building type path to be defined directly, using simple string splitting. This avoids assertion failure, thrown by compiler otherwise. Also i'm using `@:eager` meta to force building types.

Another change is related to a new behaviour of `switch` expression: case values are no longer allowed to be writable variables. Even though it should not directly impact _snow_, it prevents _mint_ from compiling with an error in keyboard translation code.

### CODE REVIEW

**Comment by CamperPR** [comment]
C:\HaxeToolkit\haxe\lib\luxe\git\phoenix/Batcher.hx:149: lines 149-152 : Local variable `_current used without being initialized, perfect fix for me :)

**Comment by ntrf** [comment]
This pull request fixes only snow. There is another pull request for luxe.

**Comment by CamperPR** [comment]
@ntrf, thanks for your answer

**Comment by darmie** [comment]
@ntrf  I applied your PR, but I am getting this error

`Main does not define type UserConfig`

**Comment by ntrf** [comment]
You need to have UserConfig type defined in your Main.hx module. See the sample: https://github.com/snowkit/snow/blob/master/samples/basic/src/Main.hx#L10. I'm not sure what version was first to introduce that, but it was before my PR.

**Comment by darmie** [comment]
Thanks, I fixed it by downgrading Haxe from 3.3 to 3.2

**Pull request closed without merging**
